export const INFORM_MOVEMENTS = [
  {
    id: 2,
    fecha: 1706155979253,
    cantidad: 10,
    costoUnitario: 1000,
    costoTotal: 10000,
    producto: {
      id: 6,
      nombre: "Producto 1",
      descripcion: "Descripcion 1",
      precio: 1000,
      categoria: {
        id: 1,
        nombre: "prueba",
        descripcion: "prueba",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 3,
    fecha: 1706206593936,
    cantidad: 30,
    costoUnitario: 100,
    costoTotal: 3000,
    producto: {
      id: 9,
      nombre: "pan",
      descripcion: "Descripcion 2",
      precio: 300,
      categoria: {
        id: 1,
        nombre: "prueba",
        descripcion: "prueba",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 4,
    fecha: 1706206719104,
    cantidad: 1,
    costoUnitario: 18000,
    costoTotal: 18000,
    producto: {
      id: 10,
      nombre: "torta",
      descripcion: "toratatatat",
      precio: 25000,
      categoria: {
        id: 3,
        nombre: "Reposteria",
        descripcion: "Resposteria",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 5,
    fecha: 1706232837584,
    cantidad: 2,
    costoUnitario: 300,
    costoTotal: 600,
    producto: {
      id: 9,
      nombre: "pan",
      descripcion: "Descripcion 2",
      precio: 300,
      categoria: {
        id: 1,
        nombre: "prueba",
        descripcion: "prueba",
      },
    },
    tipoMovimiento: {
      id: 2,
      nombre: "Venta",
      descripcion: "Venta",
      esVenta: true,
    },
  },
  {
    id: 6,
    fecha: 1706232892144,
    cantidad: 5,
    costoUnitario: 400,
    costoTotal: 2000,
    producto: {
      id: 9,
      nombre: "pan",
      descripcion: "Descripcion 2",
      precio: 300,
      categoria: {
        id: 1,
        nombre: "prueba",
        descripcion: "prueba",
      },
    },
    tipoMovimiento: {
      id: 2,
      nombre: "Venta",
      descripcion: "Venta",
      esVenta: true,
    },
  },
  {
    id: 9,
    fecha: 1706278342111,
    cantidad: 30,
    costoUnitario: 1800,
    costoTotal: 54000,
    producto: {
      id: 11,
      nombre: "Pan de molde",
      descripcion: "Pan de molde para sandwich",
      precio: 3000,
      categoria: {
        id: 2,
        nombre: "Pan",
        descripcion: "Pan caliente",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 10,
    fecha: 1706278547697,
    cantidad: 10,
    costoUnitario: 18000,
    costoTotal: 180000,
    producto: {
      id: 6,
      nombre: "Producto 1",
      descripcion: "Descripcion 1",
      precio: 1000,
      categoria: {
        id: 1,
        nombre: "prueba",
        descripcion: "prueba",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 11,
    fecha: 1706278547753,
    cantidad: 15,
    costoUnitario: 3000,
    costoTotal: 45000,
    producto: {
      id: 6,
      nombre: "Producto 1",
      descripcion: "Descripcion 1",
      precio: 1000,
      categoria: {
        id: 1,
        nombre: "prueba",
        descripcion: "prueba",
      },
    },
    tipoMovimiento: {
      id: 2,
      nombre: "Venta",
      descripcion: "Venta",
      esVenta: true,
    },
  },
  {
    id: 12,
    fecha: 1706278617922,
    cantidad: 10,
    costoUnitario: 18000,
    costoTotal: 180000,
    producto: {
      id: 6,
      nombre: "Producto 1",
      descripcion: "Descripcion 1",
      precio: 1000,
      categoria: {
        id: 1,
        nombre: "prueba",
        descripcion: "prueba",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 13,
    fecha: 1706278617986,
    cantidad: 15,
    costoUnitario: 3000,
    costoTotal: 45000,
    producto: {
      id: 6,
      nombre: "Producto 1",
      descripcion: "Descripcion 1",
      precio: 1000,
      categoria: {
        id: 1,
        nombre: "prueba",
        descripcion: "prueba",
      },
    },
    tipoMovimiento: {
      id: 2,
      nombre: "Venta",
      descripcion: "Venta",
      esVenta: true,
    },
  },
  {
    id: 19,
    fecha: 1706302405670,
    cantidad: 50,
    costoUnitario: 100,
    costoTotal: 5000,
    producto: {
      id: 17,
      nombre: "pan de leche",
      descripcion: "pan de leche",
      precio: 300,
      categoria: {
        id: 2,
        nombre: "Pan",
        descripcion: "Pan caliente",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 20,
    fecha: 1706302455836,
    cantidad: 10,
    costoUnitario: 18000,
    costoTotal: 180000,
    producto: {
      id: 17,
      nombre: "pan de leche",
      descripcion: "pan de leche",
      precio: 300,
      categoria: {
        id: 2,
        nombre: "Pan",
        descripcion: "Pan caliente",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 21,
    fecha: 1706302455882,
    cantidad: 15,
    costoUnitario: 3000,
    costoTotal: 45000,
    producto: {
      id: 17,
      nombre: "pan de leche",
      descripcion: "pan de leche",
      precio: 300,
      categoria: {
        id: 2,
        nombre: "Pan",
        descripcion: "Pan caliente",
      },
    },
    tipoMovimiento: {
      id: 2,
      nombre: "Venta",
      descripcion: "Venta",
      esVenta: true,
    },
  },
  {
    id: 22,
    fecha: 1706323985361,
    cantidad: 10,
    costoUnitario: 4000.5,
    costoTotal: 40005,
    producto: {
      id: 23,
      nombre: "pan de centeno",
      descripcion:
        "El pan de centeno es un tipo de pan elaborado con harina de centeno, la panificación muestra una miga más oscura que el pan de trigo",
      precio: 8000,
      categoria: {
        id: 2,
        nombre: "Pan",
        descripcion: "Pan caliente",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 23,
    fecha: 1706323985503,
    cantidad: 20,
    costoUnitario: 4000.5,
    costoTotal: 80010,
    producto: {
      id: 23,
      nombre: "pan de centeno",
      descripcion:
        "El pan de centeno es un tipo de pan elaborado con harina de centeno, la panificación muestra una miga más oscura que el pan de trigo",
      precio: 8000,
      categoria: {
        id: 2,
        nombre: "Pan",
        descripcion: "Pan caliente",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 24,
    fecha: 1706323985518,
    cantidad: 12,
    costoUnitario: 8000,
    costoTotal: 96000,
    producto: {
      id: 23,
      nombre: "pan de centeno",
      descripcion:
        "El pan de centeno es un tipo de pan elaborado con harina de centeno, la panificación muestra una miga más oscura que el pan de trigo",
      precio: 8000,
      categoria: {
        id: 2,
        nombre: "Pan",
        descripcion: "Pan caliente",
      },
    },
    tipoMovimiento: {
      id: 2,
      nombre: "Venta",
      descripcion: "Venta",
      esVenta: true,
    },
  },
  {
    id: 25,
    fecha: 1706332878876,
    cantidad: 12,
    costoUnitario: 1000,
    costoTotal: 12000,
    producto: {
      id: 25,
      nombre: "Pan",
      descripcion: "Pansito",
      precio: 2000,
      categoria: {
        id: 2,
        nombre: "Pan",
        descripcion: "Pan caliente",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 30,
    fecha: 1706338968938,
    cantidad: 10,
    costoUnitario: 1500,
    costoTotal: 15000,
    producto: {
      id: 6,
      nombre: "Producto 1",
      descripcion: "Descripcion 1",
      precio: 1000,
      categoria: {
        id: 1,
        nombre: "prueba",
        descripcion: "prueba",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 31,
    fecha: 1706338968944,
    cantidad: 5,
    costoUnitario: 1500,
    costoTotal: 7500,
    producto: {
      id: 9,
      nombre: "pan",
      descripcion: "Descripcion 2",
      precio: 300,
      categoria: {
        id: 1,
        nombre: "prueba",
        descripcion: "prueba",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 32,
    fecha: 1706338968948,
    cantidad: 10,
    costoUnitario: 1500,
    costoTotal: 15000,
    producto: {
      id: 6,
      nombre: "Producto 1",
      descripcion: "Descripcion 1",
      precio: 1000,
      categoria: {
        id: 1,
        nombre: "prueba",
        descripcion: "prueba",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 33,
    fecha: 1706338968955,
    cantidad: 5,
    costoUnitario: 1500,
    costoTotal: 7500,
    producto: {
      id: 9,
      nombre: "pan",
      descripcion: "Descripcion 2",
      precio: 300,
      categoria: {
        id: 1,
        nombre: "prueba",
        descripcion: "prueba",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 34,
    fecha: 1706338998417,
    cantidad: 10,
    costoUnitario: 100,
    costoTotal: 1000,
    producto: {
      id: 6,
      nombre: "Producto 1",
      descripcion: "Descripcion 1",
      precio: 1000,
      categoria: {
        id: 1,
        nombre: "prueba",
        descripcion: "prueba",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 35,
    fecha: 1706338998421,
    cantidad: 5,
    costoUnitario: 500,
    costoTotal: 2500,
    producto: {
      id: 9,
      nombre: "pan",
      descripcion: "Descripcion 2",
      precio: 300,
      categoria: {
        id: 1,
        nombre: "prueba",
        descripcion: "prueba",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 36,
    fecha: 1706338998424,
    cantidad: 10,
    costoUnitario: 100,
    costoTotal: 1000,
    producto: {
      id: 6,
      nombre: "Producto 1",
      descripcion: "Descripcion 1",
      precio: 1000,
      categoria: {
        id: 1,
        nombre: "prueba",
        descripcion: "prueba",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 37,
    fecha: 1706338998427,
    cantidad: 5,
    costoUnitario: 500,
    costoTotal: 2500,
    producto: {
      id: 9,
      nombre: "pan",
      descripcion: "Descripcion 2",
      precio: 300,
      categoria: {
        id: 1,
        nombre: "prueba",
        descripcion: "prueba",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 38,
    fecha: 1706339028041,
    cantidad: 10,
    costoUnitario: 100,
    costoTotal: 1000,
    producto: {
      id: 6,
      nombre: "Producto 1",
      descripcion: "Descripcion 1",
      precio: 1000,
      categoria: {
        id: 1,
        nombre: "prueba",
        descripcion: "prueba",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 39,
    fecha: 1706339028075,
    cantidad: 5,
    costoUnitario: 500,
    costoTotal: 2500,
    producto: {
      id: 9,
      nombre: "pan",
      descripcion: "Descripcion 2",
      precio: 300,
      categoria: {
        id: 1,
        nombre: "prueba",
        descripcion: "prueba",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 40,
    fecha: 1706339046027,
    cantidad: 10,
    costoUnitario: 100,
    costoTotal: 1000,
    producto: {
      id: 23,
      nombre: "pan de centeno",
      descripcion:
        "El pan de centeno es un tipo de pan elaborado con harina de centeno, la panificación muestra una miga más oscura que el pan de trigo",
      precio: 8000,
      categoria: {
        id: 2,
        nombre: "Pan",
        descripcion: "Pan caliente",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 41,
    fecha: 1706339046032,
    cantidad: 5,
    costoUnitario: 500,
    costoTotal: 2500,
    producto: {
      id: 17,
      nombre: "pan de leche",
      descripcion: "pan de leche",
      precio: 300,
      categoria: {
        id: 2,
        nombre: "Pan",
        descripcion: "Pan caliente",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 42,
    fecha: 1706360536991,
    cantidad: 50,
    costoUnitario: 100,
    costoTotal: 5000,
    producto: {
      id: 26,
      nombre: "Pan relleno ",
      descripcion: "pan de prueba",
      precio: 300,
      categoria: {
        id: 2,
        nombre: "Pan",
        descripcion: "Pan caliente",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 44,
    fecha: 1706362797771,
    cantidad: 5,
    costoUnitario: 3500,
    costoTotal: 17500,
    producto: {
      id: 28,
      nombre: "pan de jamon",
      descripcion:
        "Un pan dulzón relleno de pasas (sin pipos), jamón cocido y ahumado, tocineta (bacon) y aceitunas",
      precio: 5000,
      categoria: {
        id: 2,
        nombre: "Pan",
        descripcion: "Pan caliente",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 45,
    fecha: 1706362797934,
    cantidad: 10,
    costoUnitario: 3500,
    costoTotal: 35000,
    producto: {
      id: 28,
      nombre: "pan de jamon",
      descripcion:
        "Un pan dulzón relleno de pasas (sin pipos), jamón cocido y ahumado, tocineta (bacon) y aceitunas",
      precio: 5000,
      categoria: {
        id: 2,
        nombre: "Pan",
        descripcion: "Pan caliente",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
  {
    id: 46,
    fecha: 1706362797947,
    cantidad: 7,
    costoUnitario: 5000,
    costoTotal: 35000,
    producto: {
      id: 28,
      nombre: "pan de jamon",
      descripcion:
        "Un pan dulzón relleno de pasas (sin pipos), jamón cocido y ahumado, tocineta (bacon) y aceitunas",
      precio: 5000,
      categoria: {
        id: 2,
        nombre: "Pan",
        descripcion: "Pan caliente",
      },
    },
    tipoMovimiento: {
      id: 2,
      nombre: "Venta",
      descripcion: "Venta",
      esVenta: true,
    },
  },
  {
    id: 47,
    fecha: 1706364055779,
    cantidad: 3,
    costoUnitario: 30000,
    costoTotal: 90000,
    producto: {
      id: 29,
      nombre: "Torta Tres leches",
      descripcion: "torta tres leches tradicional",
      precio: 50000,
      categoria: {
        id: 3,
        nombre: "Reposteria",
        descripcion: "Resposteria",
      },
    },
    tipoMovimiento: {
      id: 1,
      nombre: "Compra",
      descripcion: "Adquision de inventario",
      esVenta: false,
    },
  },
];
