// Generated by https://quicktype.io

export interface IMovementsInform {
  id: number;
  fecha: number;
  cantidad: number;
  costoUnitario: number;
  costoTotal: number;
  producto: Producto;
  tipoMovimiento: TipoMovimiento;
}

export interface Producto {
  id: number;
  nombre: string;
  descripcion: string;
  precio: number;
  categoria: TipoMovimiento;
}

export interface TipoMovimiento {
  id: number;
  nombre: Nombre;
  descripcion: Descripcion;
  esVenta?: boolean;
}

export enum Descripcion {
  AdquisionDeInventario = "Adquision de inventario",
  PanCaliente = "Pan caliente",
  Prueba = "prueba",
  Resposteria = "Resposteria",
  Venta = "Venta",
}

export enum Nombre {
  Compra = "Compra",
  Pan = "Pan",
  Prueba = "prueba",
  Reposteria = "Reposteria",
  Venta = "Venta",
}

export interface CostReport {
  productosVendidos: { [key: string]: ProductCostInfo };
  totalVentas: number;
  totalCostos: number;
  totalGanancias: number;
}

export interface ProductCostInfo {
  cantidad: number;
  precioVentaPromedio: number;
  totalVenta: number;
  costoPromedio: number;
  totalCosto: number;
  ganancia: number;
}

export interface SalesReport {
  productosVendidos: { [key: string]: ProductSaleInfo };
  totalIngresos: number;
  totalProductosVendidos: number;
}

export interface ProductSaleInfo {
  cantidad: number;
  precioVentaPromedio: number;
  totalVenta: number;
}
